### ISSUE TITLE
Unable to cast object of type 'System.Collections.Generic.List`1[MyLab.ExceptionCondition]' to type 'System.Collections.Generic.IEnumerable`1[MyLab.Logging.ExceptionCondition]'.

### ISSUE THREAD

**Issue by ozzy-ext** [ozzy-ext-mylab/logging#2]
```
{
    "id": "0HM2QUG1JM14M:00000001",
    "msg": "Unable to cast object of type 'System.Collections.Generic.List`1[MyLab.ExceptionCondition]' to type 'System.Collections.Generic.IEnumerable`1[MyLab.Logging.ExceptionCondition]'.",
    "tech": "   at MyLab.Logging.ExceptionExtensions.GetConditions(Exception exception)
   at MyLab.Logging.ExceptionDto.Create(Exception e)
   at MyLab.LogDsl.DslLogger.CreateErrorBased(EventId eventId, Exception exception, String marker, IDslLogBuilderStrategy strategy)
   at MyLab.LogDsl.DslLogger.Error(EventId eventId, Exception exception)
   at MyLab.LogDsl.DslLoggerExtensions.Error(DslLogger logger, Exception exception)
   at MyLab.WebErrors.LogUnhandledExceptionFilter.OnException(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextExceptionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"
}
```

**Comment by ozzy-ext** [comment]
MyLab lib collision
